name: tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update readme.md 
        uses: ./
        with:
          version_file_path: '__tests__/compatibility-versions.json'
          readme_path: '__tests__/README.md'
      - name: Update readme.md backup
        if: failure()
        uses: antoine-gannat/auto-filling-by-the-code@1.0.0
        with:
          version_file_path: '__tests__/compatibility-versions.json'
          readme_path: '__tests__/README.md'
