name: tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update readme.md
        uses: antoine-gannat/auto-filling-by-the-code@1.0.0
        with:
          version_file_path: '__tests__/compatibility-versions.json'
          readme_path: '__tests__/README.md'
      - name: Commit and Push the updated README.md
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README.md on updated compatibility versions"
          git push --force --quiet "https://${GH_TOKEN}@github.com/antoine-gannat/auto-filling-by-the-code" master:master > /dev/null 2>&1
