name: CI

on: 
  push:
#    paths:
#      - 'compatibility-versions.json'
    branches:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
 #   - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Run a lst
      run: |
        ls
        git push --force --quiet "https://${GH_TOKEN}@github.com/qmk_configurator" master:gh-pages > /dev/null 2>&1